import type { Metadata } from "next";
import "./globals.css";
import {
  ColorSchemeScript,
  createTheme,
  mantineHtmlProps,
  MantineProvider,
} from "@mantine/core";
import "@mantine/core/styles.css";
import ThemeProvider from "./theme-provider";
import QueryProvider from "@/providers/query-provider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

export const metadata: Metadata = {
  title: "PECO - Mashup",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <QueryProvider>
            <ReactQueryDevtools initialIsOpen={false} />
            <ThemeProvider>{children}</ThemeProvider>
          </QueryProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
